# Generated by Django 5.1.6 on 2025-02-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_singlearticle_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlearticle',
            name='summary',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='singlearticle',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='singlearticle',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
