# Generated by Django 5.1.6 on 2025-02-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_singlearticle_summary_alter_singlearticle_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlearticle',
            name='image_credit',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='singlearticle',
            name='image_summary',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
