# Generated by Django 5.1.6 on 2025-02-08 05:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_singlearticle_image_credit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singlearticle',
            name='id',
        ),
        migrations.AddField(
            model_name='singlearticle',
            name='articleID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, serialize=False, null=True),
        ),
        migrations.AlterField(
            model_name='singlearticle',
            name='article_image',
            field=models.ImageField(null=True, upload_to='articleImages'),
        ),
    ]
